import type { Metadata } from 'next';

export const metadata: Metadata = {
 title: 'Article',
 description: 'Generated by create next app',
};

export default function Article ({
 children,
}: {
    children: React.ReactNode
}) {
 return (<div>{children}</div>);
}
